# Dependencies
markdown:         kramdown
highlighter:      rouge

permalink:           pretty

# Setup
title:            uncrtn
tagline:          'trying to communicate'
description:      'Built with <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme <a href="https://github.com/poole/lanyon" target="_blank">Lanyon</a>. <br> Hosted on Github Pages. <br> Follow <a style="color:#00baff" href="https://micro.blog/uncrtn" target="_blank">@uncrtn on Micro.blog</a>.'
              
baseurl:          ''

# About/contact
author:
  name:           ''
  url:            

paginate:         5

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/uncrtn/uncrtn.github.io
